[package]
name = "monitor-affinity"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23"  }
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.19"
xcb = { version = "1.5.0", features = ["randr"] }
