name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Test
      run: |
        sudo apt install libx11-xcb-dev
        cargo check --verbose
        cargo clippy --all-targets --all-features
        cargo test --verbose
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [ test ]
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: |
        sudo apt install libx11-xcb-dev
        cargo build --release
    - uses: actions/upload-artifact@v4.5.0
      with:
        name: monitor-affinity
        path: target/release/monitor-affinity
